# Generated by Django 3.2 on 2021-04-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer_field', models.IntegerField()),
                ('positive_field', models.PositiveIntegerField()),
                ('positive_small_field', models.PositiveSmallIntegerField()),
                ('big_integer_field', models.BigIntegerField()),
                ('float_field', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('text_field', models.TextField(max_length=20)),
                ('char_field', models.CharField(max_length=10)),
            ],
        ),
    ]
