# Generated by Django 3.2 on 2021-04-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_blog', '0003_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=50)),
                ('publications', models.ManyToManyField(to='test_blog.Publication')),
            ],
            options={
                'ordering': ('headline',),
            },
        ),
    ]
