# Generated by Django 3.2 on 2021-04-29 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_blog', '0004_article_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
    ]
