# Generated by Django 3.2 on 2021-04-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_blog', '0006_auto_20210430_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
