# Generated by Django 3.2 on 2021-04-30 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_blog', '0007_alter_author_date_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга'},
        ),
    ]
