# Generated by Django 3.2 on 2021-04-30 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Author name')),
                ('surname', models.CharField(max_length=50, verbose_name='Author surname')),
                ('city', models.CharField(choices=[('minsk', 'Minsk'), ('moskow', 'Moskow'), ('london', 'London')], help_text='Choice city', max_length=50, verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('text', models.TextField(max_length=1000, verbose_name='Article text')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.author', verbose_name='Article author')),
            ],
        ),
    ]
